network:
  version: 2
  ethernets:
    {{ (networks | selectattr('name', 'eq', 'lan') | first).interface }}:
      dhcp4: true
  vlans:
    app:
      id: 4
      link: {{ (networks | selectattr('name', 'eq', 'lan') | first).interface }}
      addresses: [ '{{ (networks | selectattr('name', 'eq', 'app') | first).base }}.228/24' ]
